[general]
port = 6432
admin_username = "postgres"
admin_password = "postgres"
autoreload = 5000

[pools.test_pool]
pool_mode = "transaction"
query_parser_enabled = true
query_parser_read_write_splitting = true
sharding_function = "pg_bigint_hash"
use_patroni = true

[pools.test_pool.users.0]
username = "test_pool_user"
password = "test"
server_username = "postgres"
server_password = "postgres"
pool_size = 10
statement_timeout = 0

[pools.test_pool.shards.0]
servers = [
	["172.30.0.2", 5432, "Auto"],
	["172.30.0.6", 5432, "Auto"],
  ["172.30.0.8", 5432, "Auto"],
]
database = "postgres"
